//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportskaOpremaNemanjaTutunovic.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public int IDKorisnika { get; set; }
        public string Mail { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Adresa { get; set; }
        public string BrTelefona { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
