//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportskaOpremaNemanjaTutunovic.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Porudzbina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Porudzbina()
        {
            this.StavkaPorudzbine = new HashSet<StavkaPorudzbine>();
        }
    
        public int PorudzbinaID { get; set; }
        public int cena { get; set; }
        public System.DateTime vreme { get; set; }
        public int IDKorisnika { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaPorudzbine> StavkaPorudzbine { get; set; }
        public virtual User User { get; set; }
    }
}
